# Generated by Django 4.2 on 2025-09-27 10:30

from django.db import migrations, models
import main.models.mixins.uid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.JSONField(default=list)),
                ('views_used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(null=True)),
                ('max_views', models.PositiveIntegerField(null=True)),
                ('allowed_ip', models.GenericIPAddressField(null=True)),
                ('password_hash', models.CharField(max_length=128, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=(models.Model, main.models.mixins.uid.UIDMixin),
        ),
    ]
