# Generated by Django 4.2 on 2025-09-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhostTransfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
