from rest_framework import generics, filters
from rest_framework.permissions import AllowAny
from NeuroRsa.serializers.keypair import KeyPairSerializer, MainKeyPairSerializer
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi


class KeyPairListCreateView(generics.ListCreateAPIView):
    serializer_class = KeyPairSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ["name"]

    def get_queryset(self):
        return self.request.user.keypairs.all().order_by("-created_at")

    @swagger_auto_schema(
        operation_summary="List all key pairs",
        operation_description=(
            "Returns all RSA key pairs generated by the authenticated user.\n\n"
            "You can also search by key pair `name`."
        ),
        manual_parameters=[
            openapi.Parameter(
                "search",
                openapi.IN_QUERY,
                description="Search keypairs by name",
                type=openapi.TYPE_STRING,
            ),
        ],
        responses={200: KeyPairSerializer(many=True)},
    )
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    @swagger_auto_schema(
        operation_summary="Generate a new RSA key pair",
        operation_description=(
            "Generates a new RSA key pair using optional passphrase (min 8 chars).\n\n"
            "**Fields:**\n"
            "- `name`: A unique label for this key pair\n"
            "- `email`: Email to bind with the key\n"
            "- `passphrase`: Optional, minimum 8 characters\n\n"
            "Returns the public and private key in response (read-only)."
        ),
        request_body=KeyPairSerializer,
        responses={
            201: KeyPairSerializer(),
            400: "Validation error (e.g. duplicate name or invalid input)",
        },
    )
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class KeyPairRetrieveUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = KeyPairSerializer

    def get_queryset(self):
        return self.request.user.keypairs.all()

    @swagger_auto_schema(
        operation_summary="Retrieve a key pair",
        operation_description="Get full details of a single key pair by ID.",
        manual_parameters=[
            openapi.Parameter(
                "pk",
                openapi.IN_PATH,
                description="ID of the key pair",
                type=openapi.TYPE_STRING,
                required=True,
            )
        ],
        responses={200: KeyPairSerializer()},
    )
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    @swagger_auto_schema(
        operation_summary="Update a key pair",
        operation_description="Update fields like `name` or `email` of a specific key pair. Private/public keys are not modified.",
        manual_parameters=[
            openapi.Parameter(
                "pk",
                openapi.IN_PATH,
                description="ID of the key pair",
                type=openapi.TYPE_STRING,
                required=True,
            )
        ],
        request_body=KeyPairSerializer,
        responses={200: KeyPairSerializer()},
    )
    def patch(self, request, *args, **kwargs):
        return super().patch(request, *args, **kwargs)

    @swagger_auto_schema(
        operation_summary="Delete a key pair",
        operation_description="Permanently delete a specific RSA key pair using its ID.",
        manual_parameters=[
            openapi.Parameter(
                "pk",
                openapi.IN_PATH,
                description="ID of the key pair",
                type=openapi.TYPE_STRING,
                required=True,
            )
        ],
        responses={204: "Key pair deleted successfully"},
    )
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class MainKeyPairCreateView(generics.CreateAPIView):
    serializer_class = MainKeyPairSerializer
    permission_classes = [AllowAny]

    @swagger_auto_schema(
        operation_summary="Create a main key pair (by passphrase)",
        operation_description=(
            "Creates a main key pair for a user based on a provided passphrase. "
            "If a user with the given passphrase already exists, it will throw an error.\n\n"
            "**This is intended for external/internal apps to generate RSA keypairs for users.**"
        ),
        request_body=MainKeyPairSerializer,
        responses={
            201: openapi.Response(
                description="Main keypair created successfully.",
                examples={
                    "application/json": {
                        "public_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----...",
                        "private_key": "-----BEGIN PGP PRIVATE KEY BLOCK-----...",
                    }
                },
            ),
            400: "User with this passphrase already exists.",
        },
    )
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)
