from rest_framework import generics, filters
from rest_framework.permissions import AllowAny
from NeuroRsa.serializers.keypair import KeyPairSerializer, MainKeyPairSerializer
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi


class KeyPairListCreateView(generics.ListCreateAPIView):
    serializer_class = KeyPairSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ["name"]

    def get_queryset(self):
        return self.request.user.keypairs.all().order_by("-created_at")

    @swagger_auto_schema(
        operation_summary="List all key pairs",
        operation_description="""
Returns all RSA key pairs generated by the authenticated user.

✅ You can search by `name` using query parameter.

**Query Parameters:**
- `search`: (optional) search keypair by name.
        """,
        manual_parameters=[
            openapi.Parameter(
                "search",
                openapi.IN_QUERY,
                description="Search keypairs by name",
                type=openapi.TYPE_STRING,
            ),
        ],
        responses={200: KeyPairSerializer(many=True)
                   },
    )
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    @swagger_auto_schema(
        operation_summary="Create a new RSA key pair",
        operation_description="""
Generates a new RSA key pair using optional passphrase (minimum 8 characters).

**Fields:**
- `name` (required): A unique label for this keypair
- `email` (optional): Email to bind with the key
- `passphrase` (optional): Minimum 8 characters

**Response:**
Returns the generated public and private key (read-only).
        """,
        request_body=KeyPairSerializer,
        responses={
            201: KeyPairSerializer(),
            400: "Validation error (e.g. duplicate name)",
        },
    )
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class KeyPairRetrieveUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = KeyPairSerializer

    def get_queryset(self):
        return self.request.user.keypairs.all()

    @swagger_auto_schema(
        operation_summary=" Retrieve key pair",
        operation_description="Fetch full details of a keypair by its ID.",
        manual_parameters=[
            openapi.Parameter("pk", openapi.IN_PATH, description="KeyPair ID", type=openapi.TYPE_STRING)
        ],
        responses={200: KeyPairSerializer()},
    )
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    @swagger_auto_schema(
        operation_summary=" Update key pair info",
        operation_description="Update fields like `name` or `email` of a specific keypair.",
        manual_parameters=[
            openapi.Parameter("pk", openapi.IN_PATH, description="KeyPair ID", type=openapi.TYPE_STRING)
        ],
        request_body=KeyPairSerializer,
        responses={200: KeyPairSerializer()},
    )
    def patch(self, request, *args, **kwargs):
        return super().patch(request, *args, **kwargs)

    @swagger_auto_schema(
        operation_summary="Delete a key pair",
        operation_description="Deletes the selected keypair using its ID.",
        manual_parameters=[
            openapi.Parameter("pk", openapi.IN_PATH, description="KeyPair ID", type=openapi.TYPE_STRING)
        ],
        responses={204: "Deleted successfully"},
    )
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class MainKeyPairCreateView(generics.CreateAPIView):
    serializer_class = MainKeyPairSerializer
    permission_classes = [AllowAny]

    @swagger_auto_schema(
        operation_summary=" Create main key pair (by passphrase)",
        operation_description="""
Creates a main RSA key pair for a user, identified by a passphrase.

**Use Case:** Intended for external/internal apps that want to generate RSA keypairs for users.

**Input:**
- `pass_phrase`: Required, acts like a pseudo-username

**Output:**
- `public_key`, `private_key`: The generated keys

❗ If the user already exists, you'll get a 400 error.
        """,
        request_body=MainKeyPairSerializer,
        responses={
            201: openapi.Response(
                description="KeyPair created successfully",
                examples={
                    "application/json": {
                        "public_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----...",
                        "private_key": "-----BEGIN PGP PRIVATE KEY BLOCK-----..."
                    }
                }
            ),
            400: "User already has a main keypair",
        },
    )
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

