# Generated by Django 4.2 on 2025-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='emoji',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='password',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
