# Generated by Django 4.2 on 2025-12-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enc_salt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_private_key_iv',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_private_key_tag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
