# Generated by Django 4.2 on 2025-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0002_tempmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailextension',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
