# Generated by Django 4.2 on 2025-07-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0003_emailextension_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecipient',
            name='recipient_type',
            field=models.CharField(choices=[('to', 'To'), ('cc', 'CC'), ('bcc', 'BCC'), ('from', 'FROM')], max_length=10),
        ),
    ]
