# Generated by Django 4.2 on 2025-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0004_alter_emailrecipient_recipient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_read_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
