# Generated by Django 4.2 on 2025-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0005_email_is_read_by_recipient_email_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_sent_success',
            field=models.BooleanField(default=False),
        ),
    ]
