# Generated by Django 4.2 on 2025-02-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0005_tempmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmail',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
