# Generated by Django 4.2 on 2025-02-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0006_alter_tempmail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
