# Generated by Django 4.2 on 2025-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0006_email_is_sent_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
        migrations.AddField(
            model_name='email',
            name='imap_uid',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.CharField(choices=[('sent', 'Sent'), ('inbox', 'Inbox'), ('draft', 'Draft'), ('trash', 'Trash'), ('spam', 'Spam')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='email',
            name='primary_email_type',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('inbox', 'Inbox'), ('draft', 'Draft'), ('trash', 'Trash'), ('spam', 'Spam')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(condition=models.Q(('imap_uid__isnull', False)), fields=('mailbox', 'imap_uid', 'primary_email_type'), name='unique_mailbox_email_uid'),
        ),
    ]
