# Generated by Django 4.2 on 2025-08-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0007_alter_email_options_email_imap_uid_email_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.CharField(choices=[('sent', 'Sent'), ('inbox', 'Inbox'), ('draft', 'Draft'), ('trash', 'Trash'), ('Junk', 'Spam')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='email',
            name='primary_email_type',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('inbox', 'Inbox'), ('draft', 'Draft'), ('trash', 'Trash'), ('Junk', 'Spam')], max_length=10, null=True),
        ),
    ]
