# Generated by Django 4.2 on 2025-08-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroDrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlink',
            name='public_key',
            field=models.CharField(default='0c1a9b689c69436fa1932a7ef26101e1', max_length=45, unique=True),
        ),
    ]
