# Generated by Django 4.2 on 2025-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroDrive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='shared_link/')),
                ('file_name', models.CharField(max_length=255)),
                ('allowed_views', models.PositiveIntegerField(blank=True, null=True)),
                ('used_views', models.PositiveIntegerField(default=0)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('s3_url', models.CharField(max_length=256)),
                ('public_key', models.CharField(default='db56b622cdf040179d7740aa04097845', max_length=45, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
