# Generated by Django 4.2 on 2025-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroDrive', '0002_alter_sharedlink_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedlink',
            name='file',
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='public_key',
            field=models.CharField(default='1017c298712d4595b93dfbf202409b9d', max_length=45, unique=True),
        ),
    ]
