# Generated by Django 4.2 on 2025-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroDrive', '0003_remove_sharedlink_file_alter_sharedlink_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlink',
            name='public_key',
            field=models.CharField(default='cff413e1c5254abeaf787a8f7d226626', max_length=45, unique=True),
        ),
    ]
