# Generated by Django 4.2 on 2025-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroDrive', '0004_alter_sharedlink_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlink',
            name='public_key',
            field=models.CharField(default='247237ad46894e30a8433fec2d64eaf4', max_length=45, unique=True),
        ),
    ]
